POS-2948 Fix IE delete issue and space as thousand separator
TorqueITS/react-number-format pull request #5
Opened 2017-05-03 22:30 UTC by jagkum

2017-05-03 22:31 UTC, jagkum commented
Changed the component version as 1.1.2-trq-0.1

2017-05-03 23:41 UTC, joeydaowang approved these changes

2017-05-03 23:48 UTC, mikhailChibel requested changes

2017-05-03 23:48 UTC, mikhailChibel commented on lib/number_format.js
> +  id: 'number_format',
Why do you need a default value for the ID. It should have no id by default unless it passed from the parent component.

2017-05-03 23:56 UTC, jagkum commented on lib/number_format.js
> +  id: 'number_format',
ok will remove it

2017-05-04 00:05 UTC, mikhailChibel approved these changes

2017-05-04 00:06 UTC, merged